package me.tbsten.koma.strict.dsl

import me.tbsten.koma.strict.InternalKomaStrictApi

/**
 * Base class of the per-handler scopes generated by koma-strict (such as `LoadingEnterScope`).
 *
 * Owns the `clearPendingActions()` passthrough that every handler scope shares, so the
 * generated subclass only has to add the whitelisted surface that depends on its own
 * declaration (`state`, `action` / `error`, `nextState`, `stayState`, `emitXxx`). The
 * `onClearPendingActions` callback is wired by the generated `states()` dispatch to koma's
 * `clearPendingActions()`.
 *
 * The @DslMarker annotations (@[me.tbsten.koma.strict.KomaStrictDsl] plus koma's
 * `@koma.core.KomaStoreDsl`) stay on the generated subclass — that is the actual handler-lambda
 * receiver — so this base intentionally carries none.
 *
 * This is generated-code-only plumbing. It is guarded by @[InternalKomaStrictApi]: opting in and
 * subclassing / referencing it by hand is unsupported and entirely at your own risk.
 */
@InternalKomaStrictApi
public abstract class HandlerScope(
    private val onClearPendingActions: () -> Unit,
) {
    /**
     * Cancels queued actions that have not started executing yet (passthrough to koma's
     * clearPendingActions).
     *
     * Note: koma's default pending-action policy discards queued actions only when a
     * transition to a *different* state class is committed. Staying (stayState) and
     * self-transitions keep them — call this to drop them explicitly.
     */
    public fun clearPendingActions() {
        onClearPendingActions()
    }
}
