package me.tbsten.koma.strict.idea.preview

import java.io.File
import java.util.Locale

/**
 * Writes the VRT verify report (`index.html`) under [reportDir].
 *
 * The page is fully self-contained: all CSS / JS is inlined ([REPORT_CSS], [REPORT_VIEWER_JS],
 * [COPY_BTN_JS] — no external CDN) and images are referenced relatively from the `actual/` /
 * `golden/` / `diff/` copies that [PreviewVrt.verify] places next to it, so the whole `report/`
 * directory can be archived or opened straight from `file://`.
 *
 * Layout: a status summary (changed / new / missing / unchanged counts) followed by one section per
 * status. Every [VrtStatus.Changed] image gets a comparison viewer with four modes — `2-up` (golden
 * and actual side by side), `slide` (wipe between the two), `blend` (opacity cross-fade) and `diff`
 * (the highlight PNG) — plus the differing pixel count and both dimensions. [VrtStatus.New] images
 * show only the actual PNG, [VrtStatus.Missing] only the golden, [VrtStatus.Unchanged] is a
 * collapsed name list (their images are not copied into the report). Each actual PNG has a
 * "Copy image" button (clipboard write with a right-click fallback when the browser refuses, e.g.
 * on `file://`). The page adapts to the viewer's light / dark theme via `prefers-color-scheme`.
 */
internal fun writeVerifyReport(results: List<VrtResult>, reportDir: File) {
    File(reportDir, "index.html").writeText(buildReportHtml(results))
}

private fun buildReportHtml(results: List<VrtResult>): String {
    val changed = results.filter { it.status == VrtStatus.Changed }
    val newOnes = results.filter { it.status == VrtStatus.New }
    val missing = results.filter { it.status == VrtStatus.Missing }
    val unchanged = results.filter { it.status == VrtStatus.Unchanged }

    val sb = StringBuilder()
    sb.append("<!DOCTYPE html>\n<html lang=\"en\">\n<head>\n")
    sb.append("<meta charset=\"utf-8\">\n")
    sb.append("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\n")
    sb.append("<title>Koma Strict — preview VRT report</title>\n")
    sb.append("<style>\n").append(REPORT_CSS).append("\n").append(COPY_BTN_CSS).append("\n</style>\n")
    sb.append("</head>\n<body>\n")

    sb.append("<header class=\"page-head\">\n")
    sb.append("  <h1>Koma Strict — preview VRT report</h1>\n")
    sb.append("  <p class=\"summary\">\n")
    sb.append(summaryChip("changed", changed.size))
    sb.append(summaryChip("new", newOnes.size))
    sb.append(summaryChip("missing", missing.size))
    sb.append(summaryChip("unchanged", unchanged.size))
    sb.append("    <span>").append(results.size).append(" images compared</span>\n")
    sb.append("  </p>\n")
    sb.append("</header>\n")

    sb.append("<main>\n")
    if (changed.isNotEmpty()) {
        sb.append(
            sectionHead(
                "Changed", changed.size,
                "Pixel content differs from the golden — inspect with the 2-up / slide / blend / diff modes.",
            ),
        )
        for (r in changed) sb.append(changedCard(r))
        sb.append("</section>\n")
    }
    if (newOnes.isNotEmpty()) {
        sb.append(sectionHead("New", newOnes.size, "Rendered now but no golden exists yet — run updatePreview to accept."))
        for (r in newOnes) {
            sb.append(
                singleImageCard(
                    r, side = "actual", badgeClass = "badge-new", badgeLabel = "new",
                    dimsText = dims(r.actualWidth, r.actualHeight), withCopy = true,
                ),
            )
        }
        sb.append("</section>\n")
    }
    if (missing.isNotEmpty()) {
        sb.append(
            sectionHead(
                "Missing", missing.size,
                "A golden exists but the scenario is no longer rendered — run updatePreview to prune.",
            ),
        )
        for (r in missing) {
            sb.append(
                singleImageCard(
                    r, side = "golden", badgeClass = "badge-missing", badgeLabel = "missing",
                    dimsText = dims(r.goldenWidth, r.goldenHeight), withCopy = false,
                ),
            )
        }
        sb.append("</section>\n")
    }
    sb.append(unchangedSection(unchanged))
    sb.append("</main>\n")

    sb.append("<footer class=\"page-foot\">Generated by <code>verifyPreview</code> · goldens under <code>snapshots/preview</code></footer>\n")
    sb.append("<script>\n").append(REPORT_VIEWER_JS).append("\n").append(COPY_BTN_JS).append("\n</script>\n")
    sb.append("</body>\n</html>\n")
    return sb.toString()
}

/** One count chip in the header summary; zero counts are dimmed via `chip-zero`. */
private fun summaryChip(label: String, count: Int): String {
    val zero = if (count == 0) " chip-zero" else ""
    return "    <span class=\"chip chip-$label$zero\">$count $label</span>\n"
}

/** Opens a `<section>` with title, count pill and blurb — callers must append `</section>`. */
private fun sectionHead(title: String, count: Int, blurb: String): String = buildString {
    append("<section class=\"status-section\">\n")
    append("  <div class=\"status-head\">\n")
    append("    <h2>").append(escapeHtml(title)).append("</h2>\n")
    append("    <span class=\"count\">").append(count).append("</span>\n")
    append("  </div>\n")
    append("  <p class=\"section-blurb\">").append(escapeHtml(blurb)).append("</p>\n")
}

/** Card for a [VrtStatus.Changed] image: metadata row + the four-mode comparison viewer. */
private fun changedCard(r: VrtResult): String {
    val name = escapeHtml(r.name)
    val shot = shotThemeClass(r.name)
    val actualSrc = "actual/$name"
    val goldenSrc = "golden/$name"
    val diffSrc = "diff/$name"
    // Locale.ROOT 固定で小数点を '.' に固定する (出力を決定的に保つ)。
    val pct = if (r.comparedPixelCount > 0) {
        String.format(Locale.ROOT, "%.2f", r.diffPixelCount * 100.0 / r.comparedPixelCount)
    } else {
        "0.00"
    }
    return buildString {
        append("<article class=\"card\">\n")
        append("  <div class=\"card-head\">\n")
        append("    <code class=\"fname\">").append(name).append("</code>\n")
        append("    <span class=\"badge badge-changed\">changed</span>\n")
        append("    <span class=\"meta\">").append(r.diffPixelCount).append(" / ").append(r.comparedPixelCount)
            .append(" px differ (").append(pct).append("%)</span>\n")
        append("    <span class=\"meta\">actual ").append(dims(r.actualWidth, r.actualHeight))
            .append(" · golden ").append(dims(r.goldenWidth, r.goldenHeight)).append("</span>\n")
        if (r.sizeMismatch) append("    <span class=\"meta meta-warn\">size mismatch</span>\n")
        append(copyButton(actualSrc))
        append("  </div>\n")
        append("  <div class=\"viewer\" data-viewer>\n")
        append("    <div class=\"mode-tabs\">\n")
        append(modeButton("two-up", "2-up", active = true))
        append(modeButton("slide", "Slide", active = false))
        append(modeButton("blend", "Blend", active = false))
        append(modeButton("diff", "Diff", active = false))
        append("    </div>\n")
        // 2-up: golden / actual を横並び (各自スクロール可能な frame 内で縮小表示)。
        append("    <div class=\"panel active\" data-panel=\"two-up\">\n")
        append("      <div class=\"two-up\">\n")
        append(twoUpFigure("golden", goldenSrc, shot))
        append(twoUpFigure("actual", actualSrc, shot))
        append("      </div>\n")
        append("    </div>\n")
        // slide: 原寸で重ね、clip-path で actual を左から拭う (ピクセル位置がズレない)。
        append("    <div class=\"panel\" data-panel=\"slide\">\n")
        append("      <div class=\"stage ").append(shot).append("\">\n")
        append("        <div class=\"overlay\">\n")
        append("          <img class=\"img-under\" src=\"").append(goldenSrc).append("\" alt=\"golden\">\n")
        append("          <img class=\"img-over\" src=\"").append(actualSrc).append("\" alt=\"actual\">\n")
        append("          <div class=\"slide-divider\"></div>\n")
        append("        </div>\n")
        append("      </div>\n")
        append("      <label class=\"ctl\">wipe — actual (left) ⇔ golden (right)")
        append("<input class=\"slide-range\" type=\"range\" min=\"0\" max=\"100\" value=\"50\"></label>\n")
        append("    </div>\n")
        // blend: 原寸で重ね、actual の不透明度をスライダーで変える。
        append("    <div class=\"panel\" data-panel=\"blend\">\n")
        append("      <div class=\"stage ").append(shot).append("\">\n")
        append("        <div class=\"overlay\">\n")
        append("          <img class=\"img-under\" src=\"").append(goldenSrc).append("\" alt=\"golden\">\n")
        append("          <img class=\"img-over\" src=\"").append(actualSrc).append("\" alt=\"actual\">\n")
        append("        </div>\n")
        append("      </div>\n")
        append("      <label class=\"ctl\">blend — golden ⇔ actual")
        append("<input class=\"blend-range\" type=\"range\" min=\"0\" max=\"100\" value=\"50\"></label>\n")
        append("    </div>\n")
        // diff: PreviewVrt が焼いたハイライト PNG (マゼンタ = 相違)。
        append("    <div class=\"panel\" data-panel=\"diff\">\n")
        append("      <div class=\"stage ").append(shot).append("\">\n")
        append("        <a href=\"").append(diffSrc).append("\" target=\"_blank\" rel=\"noopener\">")
        append("<img src=\"").append(diffSrc).append("\" alt=\"diff\"></a>\n")
        append("      </div>\n")
        append("      <p class=\"hint\">magenta = differing pixels · translucent grey = matching pixels</p>\n")
        append("    </div>\n")
        append("  </div>\n")
        append("</article>\n")
    }
}

private fun modeButton(mode: String, label: String, active: Boolean): String {
    val activeClass = if (active) " active" else ""
    return "      <button class=\"mode-btn$activeClass\" data-mode=\"$mode\" type=\"button\">$label</button>\n"
}

private fun twoUpFigure(label: String, src: String, shotClass: String): String = buildString {
    append("        <figure>\n")
    append("          <figcaption>").append(label).append("</figcaption>\n")
    append("          <div class=\"frame ").append(shotClass).append("\">\n")
    append("            <a href=\"").append(src).append("\" target=\"_blank\" rel=\"noopener\">")
    append("<img src=\"").append(src).append("\" alt=\"").append(label).append("\"></a>\n")
    append("          </div>\n")
    append("        </figure>\n")
}

/** Card for a [VrtStatus.New] (actual only) or [VrtStatus.Missing] (golden only) image. */
private fun singleImageCard(
    r: VrtResult,
    side: String,
    badgeClass: String,
    badgeLabel: String,
    dimsText: String,
    withCopy: Boolean,
): String {
    val name = escapeHtml(r.name)
    val src = "$side/$name"
    return buildString {
        append("<article class=\"card\">\n")
        append("  <div class=\"card-head\">\n")
        append("    <code class=\"fname\">").append(name).append("</code>\n")
        append("    <span class=\"badge ").append(badgeClass).append("\">").append(badgeLabel).append("</span>\n")
        append("    <span class=\"meta\">").append(side).append(" ").append(dimsText).append("</span>\n")
        if (withCopy) append(copyButton(src))
        append("  </div>\n")
        append("  <div class=\"single-body\">\n")
        append("    <div class=\"stage ").append(shotThemeClass(r.name)).append("\">\n")
        append("      <a href=\"").append(src).append("\" target=\"_blank\" rel=\"noopener\">")
        append("<img src=\"").append(src).append("\" alt=\"").append(name).append("\"></a>\n")
        append("    </div>\n")
        append("  </div>\n")
        append("</article>\n")
    }
}

private fun unchangedSection(unchanged: List<VrtResult>): String = buildString {
    append(sectionHead("Unchanged", unchanged.size, "Pixel-identical to the golden (images are not copied into the report)."))
    if (unchanged.isEmpty()) {
        append("  <p class=\"hint\">none</p>\n")
    } else {
        append("  <details class=\"unchanged-details\">\n")
        append("    <summary>Show ").append(unchanged.size).append(" file name(s)</summary>\n")
        append("    <ul>\n")
        for (r in unchanged) append("      <li>").append(escapeHtml(r.name)).append("</li>\n")
        append("    </ul>\n")
        append("  </details>\n")
    }
    append("</section>\n")
}

private fun copyButton(src: String): String =
    "    <button class=\"copy-btn\" type=\"button\" data-src=\"" + escapeHtml(src) + "\">Copy image</button>\n"

// shot 自身のテーマに合わせた下地 (diff PNG は半透明なので背景が透ける)。
private fun shotThemeClass(name: String): String =
    if (name.endsWith("-dark.png")) "shot-dark" else "shot-light"

private fun dims(width: Int?, height: Int?): String =
    if (width == null || height == null) "-" else "${width}x$height"

private fun escapeHtml(s: String): String = s
    .replace("&", "&amp;")
    .replace("<", "&lt;")
    .replace(">", "&gt;")
    .replace("\"", "&quot;")
