package me.tbsten.koma.strict.ksp.codegen

import me.tbsten.koma.strict.InternalKomaStrictApi
import me.tbsten.koma.strict.ksp.model.GroupNode
import me.tbsten.koma.strict.ksp.model.LeafNode
import me.tbsten.koma.strict.ksp.model.StateDeclarationKind
import me.tbsten.koma.strict.ksp.model.StateParent
import me.tbsten.koma.strict.ksp.model.StoreSpec
import me.tbsten.koma.strict.ksp.model.hasOwnHandlerDeclarations
import me.tbsten.koma.strict.ksp.model.nodesWithPath
import me.tbsten.koma.strict.ksp.naming.bundleScopeTypeName
import me.tbsten.koma.strict.ksp.naming.groupBuilderTypeName
import me.tbsten.koma.strict.ksp.naming.groupHandlersTypeName
import me.tbsten.koma.strict.ksp.naming.createStoreFactoryFunctionName
import me.tbsten.koma.strict.ksp.naming.handlersTypeName
import me.tbsten.koma.strict.ksp.naming.implTypeName
import me.tbsten.koma.strict.ksp.naming.restoreStoreFactoryFunctionName
import me.tbsten.koma.strict.ksp.naming.statesConfigureScopeTypeName

/**
 * Full enumeration of the **top-level type names** generated by [spec]
 * (1:1 with the declarations [appendNodeFile] actually emits), including the bundle scope
 * types of the scope-lambda form, the builder types of the builder form (`actions { ... }` /
 * `states { ... }`), and, for self-declaring groups, the composite Handlers (and its scope).
 *
 * Because the generated-type prefix is "the path concatenated without the root", same-named
 * leaves in different @StoreSpec hierarchies **within the same package** (or path
 * concatenations that coincide within one hierarchy, like `Stable.Idle` vs `StableIdle`)
 * cause top-level type redeclarations. This enumeration is the input to the frontend's
 * collision-detection diagnostic (on the core/storeSpec side).
 *
 * Private `Impl`s are included too — even file-private in Kotlin shares the JVM class name
 * `package.LoadingImpl`, so duplicates become a "Duplicate JVM class name" error.
 */
@InternalKomaStrictApi
public fun generatedTopLevelTypeNames(spec: StoreSpec): List<String> {
    val env = CodegenEnv(spec)
    return buildList {
        spec.root.nodesWithPath().forEach { (path, node) ->
            if (node is LeafNode && node.declarationKind == StateDeclarationKind.INTERFACE) {
                add(implTypeName(env.prefix(path)))
            }
            val handlers = env.handlersOf(path, node)
            handlers.forEach { handler ->
                handler.reactionType?.let(::add)
                handler.transitionsType?.let(::add)
                add(handler.scopeType)
            }
            if (handlers.isNotEmpty()) {
                val bundleType = nodeHandlersTypeName(env, path, node)
                add(bundleType)
                add(bundleScopeTypeName(bundleType))
                if (actionsBuilderSupported(handlers)) {
                    // builder 形式 (actions { ... }) の builder 型 (enter / exit 宣言つき node には生えない)
                    add(nodeActionsBuilderTypeName(env, path, node))
                }
            }
            if (node is GroupNode) {
                val groupType = groupHandlersTypeName(env.prefix(path))
                add(groupType)
                add(bundleScopeTypeName(groupType))
                // builder 形式 (states { ... }) の builder 型 (中間 sealed には常に生える)
                add(groupBuilderTypeName(env.prefix(path)))
                if (node.hasOwnHandlerDeclarations()) {
                    // 自宣言 + 子を持つ中間 sealed の合成型 (親側 param 型) とその scope
                    val compositeType = handlersTypeName(env.prefix(path))
                    add(compositeType)
                    add(bundleScopeTypeName(compositeType))
                }
            }
            if (node is StateParent && statesConfigureMembers(env, path, node).isNotEmpty()) {
                // states() の trailing escape scope (member ゼロなら非生成 = センチネル維持)
                add(statesConfigureScopeTypeName(env.prefix(path)))
            }
        }
    }
}

/**
 * Top-level **function** names generated by [spec] that must stay unique per package
 * (currently only the per-store factory functions). Two same-named factory functions from
 * different roots (`Lce` and `LceState` both yield `restoreLceStore`) would merely overload for
 * kotlinc, but they are rejected by the frontend's collision diagnostic together with
 * [generatedTopLevelTypeNames] to keep the entry points unambiguous.
 *
 * `createStoreFactoryFunctionName` is only included when `spec.initial` is non-empty, matching
 * [appendStoreFactories] which skips it otherwise — including it unconditionally would flag
 * false-positive collisions against a same-base-name root that never actually emits it.
 * `restoreStoreFactoryFunctionName` is always generated, so always included.
 */
@InternalKomaStrictApi
public fun generatedTopLevelFunctionNames(spec: StoreSpec): List<String> =
    buildList {
        if (spec.initial.isNotEmpty()) add(createStoreFactoryFunctionName(spec.root))
        add(restoreStoreFactoryFunctionName(spec.root))
    }
