package me.tbsten.koma.strict

/**
 * [DslMarker] applied to the scope types generated by koma-strict.
 *
 * Attached to generated per-handler scope types (such as `LoadingEnterScope`) so that
 * nested handler lambdas cannot accidentally call an outer handler scope's members
 * (through an implicit receiver). Generated scopes also carry koma's own `@KomaStoreDsl`
 * so the koma builder API does not leak into handler lambdas written inline in `Store {}`.
 *
 * Not intended to be applied by users directly (generated code only).
 */
@DslMarker
@Target(AnnotationTarget.CLASS)
public annotation class KomaStrictDsl
