package me.tbsten.koma.strict.ksp.core.strictStore

import com.google.devtools.ksp.symbol.KSClassDeclaration
import me.tbsten.koma.strict.ksp.core.common.fullName
import me.tbsten.koma.strict.ksp.core.common.storeFactoryFunctionName

/**
 * TODO(doc/internal/generate-strict-store-factory-dsl.md): pipeline e2e 証明用の placeholder generator。
 *   本実装 (Impl / factory / Scope / Transitions / Reaction / Handlers / facade の生成) が
 *   固まったらこのファイルごと置き換える。本実装の生成関数は cream の appendCopyFunction 同様
 *   `context(options: KomaStrictOptions, logger: KSPLogger)` を取る規約とする。
 */
internal fun Appendable.appendStoreFactoryStub(source: KSClassDeclaration) {
    val functionName = storeFactoryFunctionName(source)
    appendLine("/**")
    appendLine(" * TODO Placeholder store factory for [${source.fullName}].")
    appendLine(" *")
    appendLine(" * Generated by koma-strict-ksp to prove the KSP pipeline end-to-end. This stub will be")
    appendLine(" * replaced by the strict store factory DSL (doc/internal/generate-strict-store-factory-dsl.md).")
    appendLine(" */")
    appendLine("public fun $functionName(): Nothing =")
    appendLine("    TODO(\"koma-strict: strict store factory generation is not implemented yet.\")")
}
